### ISSUE TITLE
Adopt React

### ISSUE THREAD

**Issue by newhouseb** [newhouseb/hospitalcommunity#4]
I (@newhouseb) have written React in the past, but not recently.

The existing code uses something that's much smaller than react but also much more basic. There's not much code so far, so it's a great time for someone who is much faster at writing solid React than me to rewrite the rendering logic in React.

**Comment by johnsonfung** [comment]
I can work on this first thing tomorrow morning.

**Comment by johnsonfung** [comment]
Made a bunch of progress - should have most of the stuff refactored by EOD tomorrow.

**Comment by johnsonfung** [comment]
@newhouseb - here's how far I got tonight:
https://github.com/johnsonfung/hospitalcommunity/tree/master/app

1. I rebuilt the search and the hospital profile page in react via `create-react-app`
2. I integrated your search index and results (I fixed a bug where results would display twice).
3. I made it so keyboard controls work to highlight/navigate the results.
4. I added React Router for all the URL routing. (e.g. /hospital/144005)
5. I've connected it to Firebase for read functions (I don't know what the schema is, so I only have equipment needs showing). You can see a sample of this connecting directly to Firebase here (e.g. /hospital/330101).

Before I can add in the forms to submit needs, we should connect and talk about how you envision the flow to work. You can reach me on Facebook.

**Comment by newhouseb** [comment]
This is great! I left a few comment on individual commits on your fork.

I ran `yarn build` as well and looked at the static resources... they're big! It looks like the JS (before gzipping) is around 2MB (~1MB of that is the hospital index, which makes sense that it's huge). I'm not calibrated on modern front-end size, but is that normal?

**Comment by johnsonfung** [comment]
Honestly, I'm not sure. I've only ever used create-react-app to get started on a build, and my understanding is that it'll include the minimum recommended dependencies for a basic React build, so I can only tell you that my past projects were this size.

The only additional packages I added were react-router-dom and firebase. I think I left Bootstrap's package out and just linked to it.

I think if we get someone else on board who is a lot more versed in custom React builds they can make recommendations on what to cut. There are few images that are left from create-react-app that I can cut out that'll probably reduce the size too.

Currently working on the dynamic generation of the needs/offers.

**Comment by newhouseb** [comment]
Taken care of by @johnsonfung's diffs. Thanks for all your hard work!
